export const slider______1 = [
  {
    id: 1,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 2,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 3,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 4,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 5,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 6,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 7,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 8,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 9,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
  {
    id: 10,
    src: "../../../../../../public/assets/Images/product/section3_product/Num2/FDA-Certificate.webp",
    name: "FDA Certificate",
    detail: "FDA Certificate",
    time: "Apr 27,2009",
  },
];
