export const categorize_data = [
  {
    id: 1,
    name: "Manufactory & Processing Machinery",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Agreculture Machinery",
        submain: [
          { id: 1, name: "Agreculture Machinery" },
          { id: 2, name: "Feed processing Machinery" },
          { id: 3, name: "Livetook Machinery" },
          { id: 4, name: "Tiller" },
          { id: 5, name: "Hervitting Machine" },
        ],
      },
      {
        id: 2,
        name: "Plastic & Woodworking Machine",
        submain: [
          { id: 1, name: "plastic Machinery" },
          { id: 2, name: "Woodworking Machinery" },
          { id: 3, name: "plaotao Machinery" },
          { id: 4, name: "Injection modeling" },
          { id: 5, name: "blow Modling machine" },
        ],
      },
      {
        id: 3,
        name: "machine tools",
        submain: [
          { id: 1, name: "CNC machine tools" },
          { id: 2, name: "Lether" },
          { id: 3, name: "Gridding machine" },
          { id: 4, name: "Milling machine" },
          { id: 5, name: "Drilling machine" },
        ],
      },
      {
        id: 4,
        name: "Construction Machinery",
        submain: [
          { id: 1, name: "Buliding material making machinery" },
          { id: 2, name: "Exevetor" },
          { id: 3, name: "Lifting Equipment" },
          { id: 4, name: "concertarate Machinery" },
          { id: 5, name: "stone processing machinery" },
        ],
      },
      {
        id: 5,
        name: "other Machinery & parts",
        submain: [
          { id: 1, name: "Machinery Food" },
          { id: 2, name: "Metalic Processing Machinery" },
          { id: 3, name: "Laser Equipment" },
          { id: 4, name: "Mould" },
          { id: 5, name: "Textile Machinery & parts" },
          { id: 6, name: "Chimeical Equipment" },
          { id: 7, name: "paper machinery" },
          { id: 8, name: "Cutting & Fold-bleding Machine" },
          { id: 9, name: "Mixing Equipment" },
          { id: 10, name: "Rubber Machinery" },
          { id: 11, name: "Machinery for garment shoes" },
          { id: 12, name: "Crushing & Culling Machine" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
];
export const data_categorizer_img = [
  {
    id: 1,
    href: "#",
    name: "Feed Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num1.webp",
  },
  {
    id: 2,
    href: "#",
    name: "Brick Making Machine",
    src: "../../../public/assets/Image/all_categorize/num2.webp",
  },
  {
    id: 3,
    href: "#",
    name: "Die Casting",
    src: "../../../public/assets/Image/all_categorize/num3.webp",
  },
  {
    id: 4,
    href: "#",
    name: "Beverage Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num4.webp",
  },
  {
    id: 5,
    href: "#",
    name: "Laser Cutting Machine",
    src: "../../../public/assets/Image/all_categorize/num5.webp",
  },
  {
    id: 6,
    href: "#",
    name: "Feed Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num1.webp",
  },
  {
    id: 7,
    href: "#",
    name: "Brick Making Machine",
    src: "../../../public/assets/Image/all_categorize/num2.webp",
  },
  {
    id: 8,
    href: "#",
    name: "Die Casting",
    src: "../../../public/assets/Image/all_categorize/num3.webp",
  },
  {
    id: 9,
    href: "#",
    name: "Beverage Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num4.webp",
  },
  {
    id: 10,
    href: "#",
    name: "Laser Cutting Machine",
    src: "../../../public/assets/Image/all_categorize/num5.webp",
  },
];
export const data_sploight_slider = [
  {
    id: 1,
    href: "#",
    name: "Lifting Equipment",
    src: "../../../public/assets/Image/all_categorize/Lifting-Equipment.jpg",
    alt: "Lifting Equipment",
  },
  {
    id: 2,
    href: "#",
    name: "Agricultural Machinery",
    src: "../../../public/assets/Image/all_categorize/Agricultural-Machinery.jpg",
    alt: "Agricultural Machinery",
  },
  {
    id: 3,
    href: "#",
    name: "Metallic Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/Metallic-Processing-Machinery.jpg",
    alt: "Metallic Processing Machinery",
  },
  {
    id: 4,
    href: "#",
    name: "Machinery for Food, Beverage & Cereal",
    src: "../../../public/assets/Image/all_categorize/Machinery-for-Food-Beverage-Cereal.jpg",
    alt: "Machinery for Food, Beverage & Cereal",
  },
  {
    id: 5,
    href: "#",
    name: "Engineering & Construction Machinery",
    src: "../../../public/assets/Image/all_categorize/Engineering-Construction-Machinery.jpg",
    alt: "Engineering & Construction Machinery",
  },
  {
    id: 6,
    href: "#",
    name: "Lifting Equipment",
    src: "../../../public/assets/Image/all_categorize/Lifting-Equipment.jpg",
    alt: "Lifting Equipment",
  },
  {
    id: 7,
    href: "#",
    name: "Agricultural Machinery",
    src: "../../../public/assets/Image/all_categorize/Agricultural-Machinery.jpg",
    alt: "Agricultural Machinery",
  },
  {
    id: 8,
    href: "#",
    name: "Metallic Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/Metallic-Processing-Machinery.jpg",
    alt: "Metallic Processing Machinery",
  },
  {
    id: 9,
    href: "#",
    name: "Machinery for Food, Beverage & Cereal",
    src: "../../../public/assets/Image/all_categorize/Machinery-for-Food-Beverage-Cereal.jpg",
    alt: "Machinery for Food, Beverage & Cereal",
  },
  {
    id: 10,
    href: "#",
    name: "Engineering & Construction Machinery",
    src: "../../../public/assets/Image/all_categorize/Engineering-Construction-Machinery.jpg",
    alt: "Engineering & Construction Machinery",
  },
  ,
  {
    id: 11,
    href: "#",
    name: "Lifting Equipment",
    src: "../../../public/assets/Image/all_categorize/Lifting-Equipment.jpg",
    alt: "Lifting Equipment",
  },
  {
    id: 12,
    href: "#",
    name: "Agricultural Machinery",
    src: "../../../public/assets/Image/all_categorize/Agricultural-Machinery.jpg",
    alt: "Agricultural Machinery",
  },
  {
    id: 13,
    href: "#",
    name: "Metallic Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/Metallic-Processing-Machinery.jpg",
    alt: "Metallic Processing Machinery",
  },
  {
    id: 14,
    href: "#",
    name: "Machinery for Food, Beverage & Cereal",
    src: "../../../public/assets/Image/all_categorize/Machinery-for-Food-Beverage-Cereal.jpg",
    alt: "Machinery for Food, Beverage & Cereal",
  },
  {
    id: 15,
    href: "#",
    name: "Engineering & Construction Machinery",
    src: "../../../public/assets/Image/all_categorize/Engineering-Construction-Machinery.jpg",
    alt: "Engineering & Construction Machinery",
  },
];
export const data_all_cate = [
  {
    id: 1,
    href: "#",
    name: "Agricultural & Food Machinery",
  },
  {
    id: 2,
    href: "#",
    name: "Apparel & Textile Machinery",
  },
  {
    id: 3,
    href: "#",
    name: "Chemical & Pharmaceutical Machinery",
  },
  {
    id: 4,
    href: "#",
    name: "Engineering & Construction Machinery",
  },
  {
    id: 5,
    href: "#",
    name: "Metal, Woodworking & Stone Processing Machinery",
  },
  {
    id: 6,
    href: "#",
    name: "Mining & Metallurgy Machinery",
  },
  {
    id: 7,
    href: "#",
    name: "Plastic & Rubber Machinery",
  },
  {
    id: 8,
    href: "#",
    name: "Paper, Glass & Ceramics Machinery",
  },
  {
    id: 9,
    href: "#",
    name: "Packaging & Printing Machinery",
  },
  {
    id: 10,
    href: "#",
    name: "Casting & Forging",
  },
  {
    id: 11,
    href: "#",
    name: "General Machinery & Tools",
  },
  {
    id: 12,
    href: "#",
    name: "Other Machinery",
  },
];

export const data_all_sortbutton = [
  { id: "1", name: "Feed Pellet Making Machine", href: "#" },
  { id: "2", name: "Fish Feed Processing Machine", href: "#" },
  { id: "3", name: "Combine Harvester", href: "#" },
  { id: "4", name: "Corn Harvester", href: "#" },
  { id: "5", name: "Cotton Picker", href: "#" },
  { id: "6", name: "Livestock Cleaning And Disinfection Equipment", href: "#" },
  { id: "7", name: "Breeding And Incubation Equipment", href: "#" },
  { id: "8", name: "Rotary Tiller", href: "#" },
  { id: "9", name: "Feller Buncher", href: "#" },
  { id: "10", name: "Incense Stick Making Machine", href: "#" },
  { id: "11", name: "Feed Pellet Making Machine", href: "#" },
  { id: "12", name: "Fish Feed Processing Machine", href: "#" },
  { id: "13", name: "Combine Harvester", href: "#" },
  { id: "14", name: "Corn Harvester", href: "#" },
  { id: "15", name: "Cotton Picker", href: "#" },
  {
    id: "16",
    name: "Livestock Cleaning And Disinfection Equipment",
    href: "#",
  },
  { id: "17", name: "Breeding And Incubation Equipment", href: "#" },
  { id: "18", name: "Rotary Tiller", href: "#" },
  { id: "19", name: "Feller Buncher", href: "#" },
  { id: "20", name: "Incense Stick Making Machine", href: "#" },
  { id: "21", name: "Feed Pellet Making Machine", href: "#" },
  { id: "22", name: "Fish Feed Processing Machine", href: "#" },
  { id: "23", name: "Combine Harvester", href: "#" },
  { id: "24", name: "Corn Harvester", href: "#" },
  { id: "25", name: "Cotton Picker", href: "#" },
  {
    id: "26",
    name: "Livestock Cleaning And Disinfection Equipment",
    href: "#",
  },
  { id: "27", name: "Breeding And Incubation Equipment", href: "#" },
  { id: "28", name: "Rotary Tiller", href: "#" },
  { id: "29", name: "Feller Buncher", href: "#" },
  { id: "30", name: "Incense Stick Making Machine", href: "#" },
  { id: "31", name: "Feed Pellet Making Machine", href: "#" },
  { id: "32", name: "Fish Feed Processing Machine", href: "#" },
  { id: "33", name: "Combine Harvester", href: "#" },
  { id: "34", name: "Corn Harvester", href: "#" },
  { id: "35", name: "Cotton Picker", href: "#" },
  {
    id: "36",
    name: "Livestock Cleaning And Disinfection Equipment",
    href: "#",
  },
  { id: "37", name: "Breeding And Incubation Equipment", href: "#" },
  { id: "38", name: "Rotary Tiller", href: "#" },
  { id: "39", name: "Feller Buncher", href: "#" },
  { id: "40", name: "Incense Stick Making Machine", href: "#" },
  { id: "41", name: "Feed Pellet Making Machine", href: "#" },
  { id: "42", name: "Fish Feed Processing Machine", href: "#" },
  { id: "43", name: "Combine Harvester", href: "#" },
  { id: "44", name: "Corn Harvester", href: "#" },
  { id: "45", name: "Cotton Picker", href: "#" },
  {
    id: "46",
    name: "Livestock Cleaning And Disinfection Equipment",
    href: "#",
  },
  { id: "47", name: "Breeding And Incubation Equipment", href: "#" },
  { id: "48", name: "Rotary Tiller", href: "#" },
  { id: "49", name: "Feller Buncher", href: "#" },
  { id: "50", name: "Incense Stick Making Machine", href: "#" },
  { id: "51", name: "Feed Pellet Making Machine", href: "#" },
  { id: "52", name: "Fish Feed Processing Machine", href: "#" },
  { id: "53", name: "Combine Harvester", href: "#" },
  { id: "54", name: "Corn Harvester", href: "#" },
  { id: "55", name: "Cotton Picker", href: "#" },
  {
    id: "56",
    name: "Livestock Cleaning And Disinfection Equipment",
    href: "#",
  },
  { id: "57", name: "Breeding And Incubation Equipment", href: "#" },
  { id: "58", name: "Rotary Tiller", href: "#" },
  { id: "59", name: "Feller Buncher", href: "#" },
  { id: "60", name: "Incense Stick Making Machine", href: "#" },
];
export const Card_sl_menu = [
  {
    id: 1,
    name: "Agricultural & Food Machinery",
    submenu: [
      {
        id: 1,
        name: "Agricultural Machinery",
        href: "#",
        has_sub: true,
        submenu: [
          {
            id: 1,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 2,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 3,
            name: "Baler",
            href: "#",
          },
          {
            id: 4,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 5,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 6,
            name: "Baler",
            href: "#",
          },
          {
            id: 7,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 8,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 9,
            name: "Baler",
            href: "#",
          },
          {
            id: 10,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 11,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 12,
            name: "Baler",
            href: "#",
          },
          {
            id: 13,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 14,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 15,
            name: "Baler",
            href: "#",
          },
          {
            id: 16,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 17,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 18,
            name: "Baler",
            href: "#",
          },
          {
            id: 19,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 20,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 21,
            name: "Baler",
            href: "#",
          },
          {
            id: 21,
            name: "Agricultural Machine",
            href: "#",
          },
          {
            id: 22,
            name: "Agricultar Mower",
            href: "#",
          },
          {
            id: 23,
            name: "Baler",
            href: "#",
          },
        ],
      },
      {
        id: 2,
        name: "Commidity Making Machine",
        href: "#",
        has_sub: true,
        submenu: [
          {
            id: 1,
            name: "Busher Making Machine",
            href: "#",
          },
          {
            id: 2,
            name: "Busher Making Machine",
            href: "#",
          },
          {
            id: 3,
            name: "Busher Making Machine",
            href: "#",
          },
          {
            id: 4,
            name: "Busher Making Machine",
            href: "#",
          },
        ],
      },
      {
        id: 3,
        name: "Crane",
        has_sub: true,
        href: "#",
        submenu: [
          {
            id: 1,
            name: "Baler",
            href: "#",
          },
          {
            id: 2,
            name: "Baler",
            href: "#",
          },
          {
            id: 3,
            name: "Baler",
            href: "#",
          },
          {
            id: 4,
            name: "Baler",
            href: "#",
          },
        ],
      },
      {
        id: 4,
        name: "3D Scanner",
        href: "#",
        
      },
      {
        id: 5,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      {
        id: 6,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 7,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 8,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 9,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 10,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 11,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 12,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 13,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 14,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
      ,
      {
        id: 15,
        name: "3D Scanner",
        href: "#",
        has_sub: false,
      },
    ],
  },
];
export const data_card_menu_left_num1 = [
  {
    id: 1,
    name: "Milling Machinery",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
  {
    id: 2,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps2.webp",
    href: "#",
  },
  {
    id: 3,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
  {
    id: 4,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
  {
    id: 5,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
  {
    id: 6,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
  {
    id: 7,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
  {
    id: 8,
    name: "Grain Processing",
    src: "../../../public/assets/Image/all_categorize/ps1.webp",
    href: "#",
  },
];