export const categorize_data = [
  {
    id: 1,
    name: "Manufactory & Processing Machinery",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Agreculture Machinery",
        submain: [
          { id: 1, name: "Agreculture Machinery" },
          { id: 2, name: "Feed processing Machinery" },
          { id: 3, name: "Livetook Machinery" },
          { id: 4, name: "Tiller" },
          { id: 5, name: "Hervitting Machine" },
        ],
      },
      {
        id: 2,
        name: "Plastic & Woodworking Machine",
        submain: [
          { id: 1, name: "plastic Machinery" },
          { id: 2, name: "Woodworking Machinery" },
          { id: 3, name: "plaotao Machinery" },
          { id: 4, name: "Injection modeling" },
          { id: 5, name: "blow Modling machine" },
        ],
      },
      {
        id: 3,
        name: "machine tools",
        submain: [
          { id: 1, name: "CNC machine tools" },
          { id: 2, name: "Lether" },
          { id: 3, name: "Gridding machine" },
          { id: 4, name: "Milling machine" },
          { id: 5, name: "Drilling machine" },
        ],
      },
      {
        id: 4,
        name: "Construction Machinery",
        submain: [
          { id: 1, name: "Buliding material making machinery" },
          { id: 2, name: "Exevetor" },
          { id: 3, name: "Lifting Equipment" },
          { id: 4, name: "concertarate Machinery" },
          { id: 5, name: "stone processing machinery" },
        ],
      },
      {
        id: 5,
        name: "other Machinery & parts",
        submain: [
          { id: 1, name: "Machinery Food" },
          { id: 2, name: "Metalic Processing Machinery" },
          { id: 3, name: "Laser Equipment" },
          { id: 4, name: "Mould" },
          { id: 5, name: "Textile Machinery & parts" },
          { id: 6, name: "Chimeical Equipment" },
          { id: 7, name: "paper machinery" },
          { id: 8, name: "Cutting & Fold-bleding Machine" },
          { id: 9, name: "Mixing Equipment" },
          { id: 10, name: "Rubber Machinery" },
          { id: 11, name: "Machinery for garment shoes" },
          { id: 12, name: "Crushing & Culling Machine" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
];
export const data_categorizer_img = [
  {
    id: 1,
    href: "#",
    name: "Feed Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num1.webp",
  },
  {
    id: 2,
    href: "#",
    name: "Brick Making Machine",
    src: "../../../public/assets/Image/all_categorize/num2.webp",
  },
  {
    id: 3,
    href: "#",
    name: "Die Casting",
    src: "../../../public/assets/Image/all_categorize/num3.webp",
  },
  {
    id: 4,
    href: "#",
    name: "Beverage Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num4.webp",
  },
  {
    id: 5,
    href: "#",
    name: "Laser Cutting Machine",
    src: "../../../public/assets/Image/all_categorize/num5.webp",
  },
  {
    id: 6,
    href: "#",
    name: "Feed Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num1.webp",
  },
  {
    id: 7,
    href: "#",
    name: "Brick Making Machine",
    src: "../../../public/assets/Image/all_categorize/num2.webp",
  },
  {
    id: 8,
    href: "#",
    name: "Die Casting",
    src: "../../../public/assets/Image/all_categorize/num3.webp",
  },
  {
    id: 9,
    href: "#",
    name: "Beverage Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/num4.webp",
  },
  {
    id: 10,
    href: "#",
    name: "Laser Cutting Machine",
    src: "../../../public/assets/Image/all_categorize/num5.webp",
  },
];
export const data_sploight_slider = [
  {
    id: 1,
    href: "#",
    name: "Lifting Equipment",
    src: "../../../public/assets/Image/all_categorize/Lifting-Equipment.jpg",
    alt: "Lifting Equipment",
  },
  {
    id: 2,
    href: "#",
    name: "Agricultural Machinery",
    src: "../../../public/assets/Image/all_categorize/Agricultural-Machinery.jpg",
    alt: "Agricultural Machinery",
  },
  {
    id: 3,
    href: "#",
    name: "Metallic Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/Metallic-Processing-Machinery.jpg",
    alt: "Metallic Processing Machinery",
  },
  {
    id: 4,
    href: "#",
    name: "Machinery for Food, Beverage & Cereal",
    src: "../../../public/assets/Image/all_categorize/Machinery-for-Food-Beverage-Cereal.jpg",
    alt: "Machinery for Food, Beverage & Cereal",
  },
  {
    id: 5,
    href: "#",
    name: "Engineering & Construction Machinery",
    src: "../../../public/assets/Image/all_categorize/Engineering-Construction-Machinery.jpg",
    alt: "Engineering & Construction Machinery",
  },
  {
    id: 6,
    href: "#",
    name: "Lifting Equipment",
    src: "../../../public/assets/Image/all_categorize/Lifting-Equipment.jpg",
    alt: "Lifting Equipment",
  },
  {
    id: 7,
    href: "#",
    name: "Agricultural Machinery",
    src: "../../../public/assets/Image/all_categorize/Agricultural-Machinery.jpg",
    alt: "Agricultural Machinery",
  },
  {
    id: 8,
    href: "#",
    name: "Metallic Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/Metallic-Processing-Machinery.jpg",
    alt: "Metallic Processing Machinery",
  },
  {
    id: 9,
    href: "#",
    name: "Machinery for Food, Beverage & Cereal",
    src: "../../../public/assets/Image/all_categorize/Machinery-for-Food-Beverage-Cereal.jpg",
    alt: "Machinery for Food, Beverage & Cereal",
  },
  {
    id: 10,
    href: "#",
    name: "Engineering & Construction Machinery",
    src: "../../../public/assets/Image/all_categorize/Engineering-Construction-Machinery.jpg",
    alt: "Engineering & Construction Machinery",
  },
  ,
  {
    id: 11,
    href: "#",
    name: "Lifting Equipment",
    src: "../../../public/assets/Image/all_categorize/Lifting-Equipment.jpg",
    alt: "Lifting Equipment",
  },
  {
    id: 12,
    href: "#",
    name: "Agricultural Machinery",
    src: "../../../public/assets/Image/all_categorize/Agricultural-Machinery.jpg",
    alt: "Agricultural Machinery",
  },
  {
    id: 13,
    href: "#",
    name: "Metallic Processing Machinery",
    src: "../../../public/assets/Image/all_categorize/Metallic-Processing-Machinery.jpg",
    alt: "Metallic Processing Machinery",
  },
  {
    id: 14,
    href: "#",
    name: "Machinery for Food, Beverage & Cereal",
    src: "../../../public/assets/Image/all_categorize/Machinery-for-Food-Beverage-Cereal.jpg",
    alt: "Machinery for Food, Beverage & Cereal",
  },
  {
    id: 15,
    href: "#",
    name: "Engineering & Construction Machinery",
    src: "../../../public/assets/Image/all_categorize/Engineering-Construction-Machinery.jpg",
    alt: "Engineering & Construction Machinery",
  },
];