export const sl_data = [
  {
    id: 1,
    href: "#",
    src: "../../../public/assets/Images/a1.webp",
  },
  {
    id: 2,
    href: "#",
    src: "../../../public/assets/Images/a2.webp",
  },
  {
    id: 3,
    href: "#",
    src: "../../../public/assets/Images/a3.webp",
  },
  {
    id: 4,
    href: "#",
    src: "../../../public/assets/Images/a4.webp",
  },
  {
    id: 5,
    href: "#",
    src: "../../../public/assets/Images/a5.webp",
  },
];
export const hot_product = [
  {
    id: 1,
    name: "UPS",
  },
  { id: 2, name: "Plug" },
  { id: 3, name: "Look" },
  {
    id: 4,
    name: "Car Camera",
  },
];
export const menuSlider = [
  {
    id: 1,
    name: "Halloween-Supplies",
    src: "../../../../../public/assets/Images/slider_menu/Halloween-Supplies.jpg",
  },
  {
    id: 2,
    name: "Halloween-Supplies",
    src: "../../../../../public/assets/Images/slider_menu/Halloween-Supplies.jpg",
  },
  {
    id: 3,
    name: "Halloween-Supplies",
    src: "../../../../../public/assets/Images/slider_menu/Halloween-Supplies.jpg",
  },
  {
    id: 4,
    name: "Halloween-Supplies",
    src: "../../../../../public/assets/Images/slider_menu/Halloween-Supplies.jpg",
  },
];
export const FlexBoxSlider = [
  {
    id: 1,
    class: true,
    src: "../../../public/assets/Images/smart.png",
    pfirst: "SMART EXPO",
    psecond:
      "Reliable China Suppliers, Recommended at World's Famous Trade Shows.",
    icon: "<LuMoveRight />",
    alt: "this is test!",
    href: "#",
  },
  {
    id: 2,
    class: false,
    src: "../../../public/assets/Images/s2.webp",
    pfirst: "Secured Trading Service",
    psecond: "",
    icon: "<LuMoveRight />",
    alt: "this is test!",
  },
  {
    id: 3,
    class: false,
    src: "../../../public/assets/Images/s3.webp",
    pfirst: "STAR suplied",
    psecond: "",
    icon: "<LuMoveRight />",
    alt: "this is test!",
  },
  {
    id: 4,
    class: false,
    src: "../../../public/assets/Images/s4.webp",
    pfirst: "selected supplier",
    psecond: "",
    icon: "<LuMoveRight />",
    alt: "this is test!",
  },
];
export const right = [
  {
    id: 1,
    href: "#",
    src: "../../../public/assets/Images/w1.webp",
    name: "Hydrolic pump",
    p: "70.000+Products",
  },
  {
    id: 2,
    href: "#",
    src: "../../../public/assets/Images/w2.webp",
    name: "coffee table",
    p: "50.000+Products",
  },
  {
    id: 3,
    href: "#",
    src: "../../../public/assets/Images/w3.webp",
    name: "water purifier",
    p: "144.000+Products",
  },
  {
    id: 4,
    href: "#",
    src: "../../../public/assets/Images/w4.webp",
    name: "home furniture",
    p: "52.000+Products",
  },
  {
    id: 5,
    href: "#",
    src: "../../../public/assets/Images/w5.webp",
    name: "mobility scooter",
    p: "40.000+Products",
  },
];
export const Menu = [
  {
    id: 1,
    name: "Manufactory & Processing Machinery",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Agreculture Machinery",
        submain: [
          { id: 1, name: "Agreculture Machinery" },
          { id: 2, name: "Feed processing Machinery" },
          { id: 3, name: "Livetook Machinery" },
          { id: 4, name: "Tiller" },
          { id: 5, name: "Hervitting Machine" },
        ],
      },
      {
        id: 2,
        name: "Plastic & Woodworking Machine",
        submain: [
          { id: 1, name: "plastic Machinery" },
          { id: 2, name: "Woodworking Machinery" },
          { id: 3, name: "plaotao Machinery" },
          { id: 4, name: "Injection modeling" },
          { id: 5, name: "blow Modling machine" },
        ],
      },
      {
        id: 3,
        name: "machine tools",
        submain: [
          { id: 1, name: "CNC machine tools" },
          { id: 2, name: "Lether" },
          { id: 3, name: "Gridding machine" },
          { id: 4, name: "Milling machine" },
          { id: 5, name: "Drilling machine" },
        ],
      },
      {
        id: 4,
        name: "Construction Machinery",
        submain: [
          { id: 1, name: "Buliding material making machinery" },
          { id: 2, name: "Exevetor" },
          { id: 3, name: "Lifting Equipment" },
          { id: 4, name: "concertarate Machinery" },
          { id: 5, name: "stone processing machinery" },
        ],
      },
      {
        id: 5,
        name: "other Machinery & parts",
        submain: [
          { id: 1, name: "Machinery Food" },
          { id: 2, name: "Metalic Processing Machinery" },
          { id: 3, name: "Laser Equipment" },
          { id: 4, name: "Mould" },
          { id: 5, name: "Textile Machinery & parts" },
          { id: 6, name: "Chimeical Equipment" },
          { id: 7, name: "paper machinery" },
          { id: 8, name: "Cutting & Fold-bleding Machine" },
          { id: 9, name: "Mixing Equipment" },
          { id: 10, name: "Rubber Machinery" },
          { id: 11, name: "Machinery for garment shoes" },
          { id: 12, name: "Crushing & Culling Machine" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 2,
    name: "consumer electronics",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "CellPhone & Accessorizes",
        submain: [
          { id: 1, name: "Bluetooth & Headset" },
          { id: 2, name: "Mobile phone Charger" },
          { id: 3, name: "Power bank" },
          { id: 4, name: "mobile phone LCD" },
          { id: 5, name: "Smart Phone" },
        ],
      },
      {
        id: 2,
        name: "Digital Devices",
        submain: [
          { id: 1, name: "Battery & Charger" },
          { id: 2, name: "Wearable Device" },
          { id: 3, name: "Digital photo frame" },
          { id: 4, name: "Digital camera" },
          { id: 5, name: "Smart glasess" },
        ],
      },
      {
        id: 3,
        name: "Audio & Vedio",
        submain: [
          { id: 1, name: "Display & Accessories" },
          { id: 2, name: "Audio & Sets" },
          { id: 3, name: "LCD Display" },
          { id: 4, name: "LCD Module" },
          { id: 5, name: "Prfessinal Audio" },
          { id: 6, name: "TV & Parts" },
          { id: 7, name: "Amplifier" },
          { id: 8, name: "Video" },
          { id: 9, name: "Portable Audio" },
          { id: 10, name: "Home theatre Systems" },
          { id: 11, name: "HDMI Cable" },
          { id: 12, name: "Radio" },
        ],
      },
      {
        id: 4,
        name: "Household Appliances",
        submain: [
          { id: 1, name: "Air Condition" },
          { id: 2, name: "Refregerator & Freezer & Parts" },
          { id: 3, name: "Water Heater & Components" },
          { id: 4, name: "Electronic Fan" },
          { id: 5, name: "Water Treatment Equipment" },
          { id: 6, name: "Food Blender" },
          { id: 7, name: "Photographic Apparatus" },
          { id: 8, name: "Gas Burner & Gas Stove" },
          { id: 9, name: "Solar Water Heater" },
          { id: 11, name: "Electrical Kettle" },
          { id: 12, name: "Entertaiments Electronic" },
          { id: 13, name: "Dehomidiffer" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 3,
    name: "industrial Equipment & components",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Pumps",
        submain: [
          { id: 1, name: "Pump & Vacum Equipments" },
          { id: 2, name: "Water Pumps" },
          { id: 3, name: "Centifigal Pumps" },
          { id: 4, name: "Vaccum pumps" },
          { id: 5, name: "Pressure Pumps" },
        ],
      },
      {
        id: 2,
        name: "Industrial Valves",
        submain: [
          { id: 1, name: "Valves" },
          { id: 2, name: "Ball Valves" },
          { id: 3, name: "Gate Valves" },
          { id: 4, name: "Check Valves" },
          { id: 5, name: "Solonied Valves" },
        ],
      },
      {
        id: 3,
        name: "Power & Generator",
        submain: [
          { id: 1, name: "Power & Generator Sets" },
          { id: 2, name: "Diesel Generator" },
          { id: 3, name: "Gasolline Generator" },
          { id: 4, name: "Gas Generator" },
          { id: 5, name: "Wind Generator" },
        ],
      },
      {
        id: 4,
        name: "Fastener & Fittings",
        submain: [
          { id: 1, name: "Bolts" },
          { id: 2, name: "Combination & Joint Fittings" },
          { id: 3, name: "Screw" },
          { id: 4, name: "Nut" },
          { id: 5, name: "Flange" },
        ],
      },
      {
        id: 5,
        name: "Purifier & Filter",
        submain: [
          { id: 1, name: "Filteration Equipments" },
          { id: 2, name: "Air Filter" },
          { id: 3, name: "Reverse Oamioaia System" },
          { id: 4, name: "Industrial Water Filter" },
          { id: 5, name: "Oil Filter" },
        ],
      },
      {
        id: 6,
        name: "other equipments & parts ",
        submain: [
          { id: 1, name: "Bearing" },
          { id: 2, name: "compressor" },
          { id: 3, name: "seeling & Gaskets" },
          { id: 4, name: "Welding Equipments" },
          { id: 5, name: "Cleaning Machine" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 4,
    name: "Electrical & electronic",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Optical Fibire,Cable & wire",
        submain: [
          { id: 1, name: "Electric,Wire & Cable" },
          { id: 2, name: "Power Cable" },
          { id: 3, name: "Optical Fiber" },
          { id: 4, name: "Communication Cable" },
          { id: 5, name: "Audio & Video Cable" },
        ],
      },
      {
        id: 2,
        name: "Motors",
        submain: [
          { id: 1, name: "Electronic motor" },
          { id: 2, name: "AC Motor" },
          { id: 3, name: "DC Motor" },
          { id: 4, name: "Asynchronous Motor" },
          { id: 5, name: "Stepper Motor" },
        ],
      },
      {
        id: 3,
        name: "Power supply & Disturbution",
        submain: [
          { id: 1, name: "Power Transmition & transformer" },
          { id: 2, name: "Raley & Contactor" },
          { id: 3, name: "Power Adaptor" },
          { id: 4, name: "Voltage Regulator" },
          { id: 5, name: "LED Power Supply" },
        ],
      },
      {
        id: 4,
        name: "Telecome & Broadcasting ",
        submain: [
          { id: 1, name: "Fibre optic Equipments" },
          { id: 2, name: "Communication Module" },
          { id: 3, name: "Antenna" },
          { id: 4, name: "Radio & TV Broadcasting" },
          { id: 5, name: "Satellite" },
        ],
      },
      {
        id: 5,
        name: "Electronic Components",
        submain: [
          { id: 1, name: "Connector & Terminal" },
          { id: 2, name: "Sensor" },
          { id: 3, name: "Switch" },
          { id: 4, name: "Circuit Board" },
          { id: 5, name: "Breaker & portector" },
          { id: 6, name: "Transformer" },
          { id: 7, name: "Sockets" },
          { id: 8, name: "Terminals" },
          { id: 9, name: "Remotes Controls" },
          { id: 10, name: "Inventor" },
          { id: 11, name: "Electronic Tube" },
          { id: 12, name: "Capcitior" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 5,
    name: "constraction & decoration",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Bathroom & Kitchen",
        submain: [
          { id: 1, name: "Bathtub" },
          { id: 2, name: "Basin Faucet" },
          { id: 3, name: "Bathroom Basin & Sink" },
          { id: 4, name: "Kitchen Mixer & Faucet" },
          { id: 5, name: "Shower Head" },
        ],
      },
      {
        id: 2,
        name: "Door & Window",
        submain: [
          { id: 1, name: "Metal Window" },
          { id: 2, name: "Automatic Door" },
          { id: 3, name: "Glass Door" },
          { id: 4, name: "Security Door" },
          { id: 5, name: "Plastic Door" },
        ],
      },
      {
        id: 3,
        name: "Finished & Structural Materials",
        submain: [
          { id: 1, name: "Wire Mesh" },
          { id: 2, name: "Pipe Fittings" },
          { id: 3, name: "Aluminum Profile" },
          { id: 4, name: "Building Glass" },
          { id: 5, name: "Plywood" },
          { id: 6, name: "Window" },
          { id: 7, name: "Ceiling" },
          { id: 8, name: "Mirror" },
          { id: 9, name: "Aluminum Composite Panel" },
          { id: 10, name: "Wallpaper" },
          { id: 11, name: "Fireplace, Stove & Parts" },
          { id: 12, name: "Composite Pipe & Tube" },
        ],
      },
      {
        id: 4,
        name: "Tiles & Flooring",
        submain: [
          { id: 1, name: "Plastic Floor" },
          { id: 2, name: "Roof Tile" },
          { id: 3, name: "Wood Plastic Composite Flooring" },
          { id: 4, name: "Floor Tile" },
          { id: 5, name: "Laminate Flooring" },
          { id: 6, name: "Mosaic Tile" },
          { id: 7, name: "Engineered Wood Flooring" },
          { id: 8, name: "Wall Tile" },
          { id: 9, name: "Rustic Tile" },
          { id: 10, name: "Polished Tile" },
          { id: 11, name: "Anti-static Flooring" },
          { id: 12, name: "Bamboo Floor" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 6,
    name: "light industrial",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Kitchenware",
        submain: [
          { id: 1, name: "Kitchen Implements" },
          { id: 2, name: "Tableware" },
          { id: 3, name: "Cookware" },
          { id: 4, name: "Bakeware" },
          { id: 5, name: "Vacuum Flask & Thermos" },
        ],
      },
      {
        id: 2,
        name: "Bedding",
        submain: [
          { id: 1, name: "Bedding Set" },
          { id: 2, name: "Blanket" },
          { id: 3, name: "Mattress" },
          { id: 4, name: "Bed Pillow" },
          { id: 5, name: "Backrest Pillow & Cushion" },
        ],
      },
      {
        id: 3,
        name: "Household Cleaning",
        submain: [
          { id: 1, name: "Dustbin" },
          { id: 2, name: "Garbage Bag" },
          { id: 3, name: "Laundry Detergent" },
          { id: 4, name: "Mop" },
          { id: 5, name: "Cleaning Brush" },
        ],
      },
      {
        id: 4,
        name: "Beauty & Personal Care",
        submain: [
          { id: 1, name: "Hotel Amenities" },
          { id: 2, name: "Makeup" },
          { id: 3, name: "Oral Care" },
          { id: 4, name: "Skin Cleaning Tools" },
          { id: 5, name: "Perfume" },
        ],
      },
      {
        id: 5,
        name: "Household & Garden",
        submain: [
          { id: 1, name: "Disposable Products" },
          { id: 2, name: "Household Plastic Products" },
          { id: 3, name: "Baby Diapers" },
          { id: 4, name: "Plastic Tube, Pipe & Hose" },
          { id: 5, name: "Flower Pot & Planter" },
          { id: 6, name: "Storage & Organization" },
          { id: 7, name: "Rack, Shelf, Holder & Hanger" },
          { id: 8, name: "Umbrella" },
          { id: 9, name: "Lawn Mower" },
          { id: 10, name: "Bottle" },
          { id: 11, name: "Pest Control" },
          { id: 12, name: "Garden Sprayer" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 7,
    name: "Auto motorcycle parts",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Auto Parts & Accessories",
        submain: [
          { id: 1, name: "Auto Parts" },
          { id: 2, name: "Brake" },
          { id: 3, name: "Wheel Hub, Rim & Spoke" },
          { id: 4, name: "Auto Filter" },
          { id: 5, name: "Auto Electrical System" },
          { id: 6, name: "Auto Bearing" },
          { id: 7, name: "Auto Steering Systems" },
          { id: 8, name: "Car Electronics" },
          { id: 9, name: "Car Tire" },
          { id: 10, name: "Shock Absorber" },
          { id: 11, name: "Auto Sensor" },
          { id: 12, name: "Auto Winch" },
        ],
      },
      {
        id: 2,
        name: "Car Parts & Accessories",
        submain: [
          { id: 1, name: "Car Accessories" },
          { id: 2, name: "Car Light & Auto Mirror" },
          { id: 3, name: "Wiper Blade, Arm & Motor" },
          { id: 4, name: "Car Seat" },
          { id: 5, name: "Car Glass & Window" },
        ],
      },
      {
        id: 3,
        name: "Motorcycle Parts & Accessories",
        submain: [
          { id: 1, name: "Motorcycle Body Parts" },
          { id: 2, name: "Motorcycle Engine" },
          { id: 3, name: "Motorcycle Helmets" },
          { id: 4, name: "Motorcycle Battery" },
          { id: 5, name: "Motorcycle Shock Absorber" },
        ],
      },
      {
        id: 4,
        name: "Auto Repair & Decoration",
        submain: [
          { id: 1, name: "Car Decoration" },
          { id: 2, name: "Car Maintenance" },
          { id: 3, name: "Car Lift" },
          { id: 4, name: "Auto Painting Equipment" },
          { id: 5, name: "Automotive Test Equipment" },
        ],
      },
      {
        id: 5,
        name: "Auto Engine & Parts",
        submain: [
          { id: 1, name: "Fuel System" },
          { id: 2, name: "Exhaust System" },
          { id: 3, name: "Crank Mechanism" },
          { id: 4, name: "Ignition System" },
          { id: 5, name: "Auto Engine" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 8,
    name: "Apparel & accessories",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Ready to Wear",
        submain: [
          { id: 1, name: "Sports Wear" },
          { id: 2, name: "T-Shirt" },
          { id: 3, name: "Underwear" },
          { id: 4, name: "Jacket" },
          { id: 5, name: "Swimsuit" },
          { id: 6, name: "Pants & Trousers" },
          { id: 7, name: "Dresses" },
          { id: 8, name: "Children's Apparel" },
          { id: 9, name: "Sweater" },
          { id: 10, name: "Denim Clothing" },
          { id: 11, name: "Down & Winter Apparel" },
          { id: 12, name: "Wedding Dresses" },
        ],
      },
      {
        id: 2,
        name: "Footwear & Headwear",
        submain: [
          { id: 1, name: "Shoes" },
          { id: 2, name: "Athletic & Sports Shoes" },
          { id: 3, name: "Sock & Stocking" },
          { id: 4, name: "Slippers" },
          { id: 5, name: "Work & Safety Shoes" },
          { id: 6, name: "Shoes Parts & Accessories" },
          { id: 7, name: "Athletic & Sports Shoes" },
          { id: 8, name: "Leisure & Comfort Shoes" },
          { id: 9, name: "Boots" },
          { id: 10, name: "Children's Shoes" },
          { id: 11, name: "Sandals" },
          { id: 12, name: "Sports CapsWarm Caps" },
        ],
      },
      {
        id: 3,
        name: "Work & Safety Apparel",
        submain: [
          { id: 1, name: "Work & Safety Gloves" },
          { id: 2, name: "Safety & Protective Apparel" },
          { id: 3, name: "Reflective Safety Clothing" },
          { id: 4, name: "Work Clothes" },
          { id: 5, name: "Uniform" },
        ],
      },
      {
        id: 4,
        name: "Apparel Accessories",
        submain: [
          { id: 1, name: "Gloves & Mittens" },
          { id: 2, name: "Clothing Accessories" },
          { id: 3, name: "Scarf" },
          { id: 4, name: "Belt & Accessories" },
          { id: 5, name: "Necktie & Bow Tie" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 9,
    name: "lights",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "LED Interior Lighting",
        submain: [
          { id: 1, name: "LED Bulb Light" },
          { id: 2, name: "LED Panel Light" },
          { id: 3, name: "LED Down Light" },
          { id: 4, name: "LED Spotlight" },
          { id: 5, name: "LED High Bay Light" },
          { id: 6, name: "LED Tube" },
          { id: 7, name: "LED Pendant Light" },
          { id: 8, name: "LED Ceiling Light" },
          { id: 9, name: "LED Wall Light" },
          { id: 10, name: "Candle Light" },
          { id: 11, name: "LED Cup" },
          { id: 12, name: "Dimmable Bulb" },
        ],
      },
      {
        id: 2,
        name: "LED Professional Lighting",
        submain: [
          { id: 1, name: "LED Grow Light" },
          { id: 2, name: "LED Flashlight" },
          { id: 3, name: "LED PAR Light" },
          { id: 4, name: "LED Headlamp" },
          { id: 5, name: "LED Traffic Light" },
        ],
      },
      {
        id: 3,
        name: "LED Outdoor Lighting",
        submain: [
          { id: 1, name: "Outdoor Lighting" },
          { id: 2, name: "LED Street Light" },
          { id: 3, name: "LED Floodlight" },
          { id: 4, name: "LED Garden Light" },
          { id: 5, name: "LED Wall Washer" },
        ],
      },
      {
        id: 4,
        name: "Professional Lighting",
        submain: [
          { id: 1, name: "LED Display" },
          { id: 2, name: "Stage Lighting" },
          { id: 3, name: "Ultraviolet Lamp" },
          { id: 4, name: "Camping Light" },
          { id: 5, name: "Stage Equments" },
        ],
      },
      {
        id: 5,
        name: "Lighting Decoration",
        submain: [
          { id: 1, name: "LED Strip Light" },
          { id: 2, name: "Rope Light" },
          { id: 3, name: "Lantern" },
          { id: 4, name: "Tiffany Lamp" },
          { id: 5, name: "Metal Light" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 10,
    name: "sporting good",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Indoor Sports & Fitness",
        submain: [
          { id: 1, name: "Sports Protection" },
          { id: 2, name: "Dumbbell" },
          { id: 3, name: "Treadmill" },
          { id: 4, name: "Exercise Bike" },
          { id: 5, name: "Outdoor Fitness Equipment" },
          { id: 6, name: "Trampoline" },
          { id: 7, name: "Martial Arts & Boxing Supplies" },
          { id: 8, name: "Billiards" },
          { id: 9, name: "Bow, Arrow & Shooting Equipment" },
          { id: 10, name: "AB Exerciser" },
          { id: 11, name: "Bowling Equipment" },
          { id: 12, name: "Dart & Dart Board" },
        ],
      },
      {
        id: 2,
        name: "Outdoor Sports & Facilities",
        submain: [
          { id: 1, name: "Golf Cart" },
          { id: 2, name: "Balance Vehicle" },
          { id: 3, name: "ATV, Quad & Parts" },
          { id: 4, name: "Skateboard" },
          { id: 5, name: "Football & Soccer Equipment" },
          { id: 6, name: "Diving Equipment" },
          { id: 7, name: "Swimming Supplies" },
          { id: 8, name: "Kayak" },
          { id: 9, name: "Skateboard" },
          { id: 10, name: "Kick Scooter & Surfing Scooter" },
          {
            id: 11,
            name: "Badminton Set, Racket & NetBasketball & Basketball Equipment",
          },
          { id: 10, name: "Go Kart & Parts" },
        ],
      },
      {
        id: 3,
        name: "Recreation Supplies",
        submain: [
          { id: 1, name: "Pet Supplies" },
          { id: 2, name: "Camping & Outdoor Gear" },
          { id: 3, name: "Tent" },
          { id: 4, name: "Amusement Park" },
          { id: 5, name: "Fishing Tackle" },
          { id: 1, name: "Recreational Boat" },
          { id: 2, name: "Yoga Supplies" },
          { id: 3, name: "Barbecue" },
          { id: 4, name: "Beach Mat & Picnic Blanket" },
          { id: 5, name: "Equestrian Equipment" },
          { id: 3, name: "Hammock" },
          { id: 4, name: "Piano" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 11,
    name: "transportation",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Cycles & Parts",
        submain: [
          { id: 1, name: "Motorcycle Parts & Accessories" },
          { id: 2, name: "Bike" },
          { id: 3, name: "Tricycle & Parts" },
          { id: 4, name: "Bicycle Parts & Accessories" },
          { id: 5, name: "Motorcycle" },
        ],
      },
      {
        id: 2,
        name: "Electric Vehicles",
        submain: [
          { id: 1, name: "Electric Vehicle & Parts" },
          { id: 2, name: "Electric Bike" },
          { id: 3, name: "Electric Motorcycle" },
          { id: 4, name: "Electric Tricycle" },
          { id: 5, name: "Handicap Scooter" },
        ],
      },
      {
        id: 3,
        name: "Specialized Vehicles",
        submain: [
          { id: 1, name: "Trailer" },
          { id: 2, name: "Forklifts & Parts" },
          { id: 3, name: "Garbage Truck" },
          { id: 4, name: "Mixer Truck" },
          { id: 5, name: "Fire Truck" },
        ],
      },
      {
        id: 4,
        name: "Elevators & Lifts",
        submain: [
          { id: 1, name: "Elevator & Funicular Car" },
          { id: 2, name: "Passenger Elevator" },
          { id: 3, name: "Freight Elevator" },
          { id: 4, name: "Sightseeing Elevator" },
          { id: 5, name: "Escalator" },
        ],
      },
      {
        id: 5,
        name: "Cargo & Storage",
        submain: [
          { id: 1, name: "Storage Racks" },
          { id: 2, name: "Barrow, Trolley & Cart" },
          { id: 3, name: "Pallets" },
          { id: 4, name: "Industrial Plastic Containers" },
          { id: 5, name: "Storge Cage" },
        ],
      },
      {
        id: 6,
        name: "Boats & Marine Parts",
        submain: [
          { id: 1, name: "Boat Fenders" },
          { id: 2, name: "Marine Engines" },
          { id: 3, name: "Speed Boat" },
          { id: 4, name: "Boat Anchors" },
          { id: 5, name: "Marine Airbags" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 12,
    name: "arts",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Jewelry & Accessories",
        submain: [
          { id: 1, name: "Fashion Accessories" },
          { id: 2, name: "Hair Products" },
          { id: 3, name: "Jewelry & Accessories" },
          { id: 4, name: "Sunglasses" },
          { id: 5, name: "Lanyard" },
        ],
      },
      {
        id: 2,
        name: "Crafts by Material",
        submain: [
          { id: 1, name: "Metal Crafts" },
          { id: 2, name: "Resin Craft" },
          { id: 3, name: "Glass Crafts" },
          { id: 4, name: "Wooden Crafts" },
          { id: 5, name: "Crystal Crafts" },
        ],
      },
      {
        id: 3,
        name: "Gifts & Decoration",
        submain: [
          { id: 1, name: "Festival & Party Supplies" },
          { id: 2, name: "Candle & Candle Holders" },
          { id: 3, name: "Badge" },
          { id: 4, name: "Key Chain" },
          { id: 5, name: "Flag & Banner" },
          { id: 6, name: "Carving & Sculpture" },
          { id: 7, name: "Artificial Crafts" },
          { id: 8, name: "Ribbon" },
          { id: 9, name: "Flower, Bonsai & Decorative Plant" },
          { id: 10, name: "Photo Frame & Picture Frame" },
          { id: 11, name: "Oil Painting" },
          { id: 12, name: "Fridge Magnets" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 13,
    name: "Health and medicine",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Massagers",
        submain: [
          { id: 1, name: "Massage Chair" },
          { id: 2, name: "Massage Table & Bed" },
          { id: 3, name: "Foot Massager" },
          { id: 4, name: "Massage Cushion" },
          { id: 5, name: "Massage Belt" },
        ],
      },
      {
        id: 2,
        name: "Medical Equipments",
        submain: [
          { id: 1, name: "Beauty Equipment" },
          { id: 2, name: "Medical Diagnosis Equipment" },
          { id: 3, name: "Dental Equipment & Supplies" },
          { id: 4, name: "Physical Therapy Equipment" },
          { id: 5, name: "Disinfect Equipment & Sterilizer" },
        ],
      },
      {
        id: 3,
        name: "Medical Supplies",
        submain: [
          { id: 1, name: "Disposable Medical Supplies" },
          { id: 2, name: "Bandage" },
          { id: 3, name: "Surgical Supplies" },
          { id: 4, name: "First Aid Kit" },
        ],
      },
      {
        id: 4,
        name: "Medical Implements",
        submain: [
          { id: 1, name: "Surgical Equipment" },
          { id: 2, name: "Surgical Instrument" },
          { id: 3, name: "Universal Medical Implement" },
          { id: 4, name: "Dental Handpiece" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 14,
    name: "computer products",
    class: false,
    mainDiv: [
      {
        id: 1,
        name: "Printing Machinery & Materials",
        submain: [
          { id: 1, name: "Printing Machinery" },
          { id: 2, name: "Printing Materials" },
          { id: 3, name: "Digital Printing Machine" },
          { id: 4, name: "Screen Printer" },
          { id: 5, name: "Printing Inks" },
        ],
      },
      {
        id: 2,
        name: "Packing & Packaging Machinery",
        submain: [
          { id: 1, name: "Packing Machinery" },
          { id: 2, name: "Filling Machine" },
          { id: 3, name: "Sealing Machine" },
          { id: 4, name: "Bag Making Machine" },
          { id: 5, name: "Coding Machine" },
        ],
      },
      {
        id: 3,
        name: "Package & Conveyance",
        submain: [
          { id: 1, name: "Packaging Bags" },
          { id: 2, name: "Packaging Bottles" },
          { id: 3, name: "Packaging Boxes" },
          { id: 4, name: "Lids, Bottle Caps & Closers" },
          { id: 5, name: "Packaging Tubes" },
        ],
      },
      {
        id: 4,
        name: "Pre & Post-Press Equipments",
        submain: [
          { id: 1, name: "Post-Press Equipment" },
          { id: 2, name: "Paper Cutter" },
          { id: 3, name: "Die Cutting Machine" },
          { id: 4, name: "Pre-Press Equipment" },
          { id: 5, name: "Laminating Machine" },
        ],
      },
    ],
    textBlue: "More categorize",
  },
  {
    id: 15,
    name: "More Categorize",
    class: true,
    mainDiv: [
      {
        id: 1,
        name: "Chemicals",
        mainSubmenu: [
          {
            id: 1,
            name: "Rubber & Plastic",
            link: [
              { id: 1, name: "Plastic Sheet, Board & Panel" },
              { id: 2, name: "Plastic Materials" },
              { id: 3, name: "Rubber Tube, Pipe & Hose" },
              { id: 4, name: "Polymer & Resin" },
              { id: 5, name: "Plastic Pipe & Tube" },
              { id: 6, name: "Plastic Film" },
              { id: 7, name: "Rubber Sheet & Mat" },
              { id: 8, name: "Rubber Seal" },
              { id: 9, name: "Rubber Materials" },
              { id: 10, name: "Plastic Rod" },
              { id: 11, name: "Rubber Belt" },
              { id: 12, name: "Plastic Strap & Tape" },
            ],
          },
          {
            id: 2,
            name: "Paint & Pigment",
            link: [
              { id: 1, name: "Paint & Coating" },
              { id: 2, name: "Pigment & Dye" },
              { id: 3, name: "Inorganic Pigment" },
              { id: 4, name: "Car Paint" },
              { id: 5, name: "Direct Dye" },
            ],
          },
          {
            id: 3,
            name: "Inorganic Chemicals",
            link: [
              { id: 1, name: "Adhesive" },
              { id: 2, name: "FRP/GRP" },
              { id: 3, name: "Phosphate" },
              { id: 4, name: "Sulfide" },
              { id: 5, name: "Fiberglass Yarn" },
            ],
          },
        ],
      },
      {
        id: 2,
        name: "Tools & Hardware",
        mainSubmenu: [
          {
            id: 1,
            name: "Hand Tools",
            link: [
              { id: 1, name: "Hand Tool Set" },
              { id: 2, name: "Pliers" },
              { id: 3, name: "Knife" },
              { id: 4, name: "Electric Wrench" },
              { id: 5, name: "Hammer" },
            ],
          },
          {
            id: 2,
            name: "Power Tools",
            link: [
              { id: 1, name: "Power Tool Accessories" },
              { id: 2, name: "Electric Drill" },
              { id: 3, name: "Electric Saw" },
              { id: 4, name: "Electric Screwdriver" },
              { id: 5, name: "Rotary Hammer" },
            ],
          },
          {
            id: 3,
            name: "Hardware",
            link: [
              { id: 1, name: "Hardware Accessories" },
              { id: 2, name: "Home Hardware" },
              { id: 3, name: "Machine Hardware" },
              { id: 4, name: "Brackets" },
              { id: 5, name: "Building Hardware" },
            ],
          },
          {
            id: 4,
            name: "Diamond Tools",
            link: [
              { id: 1, name: "Diamond Saw Blade" },
              { id: 2, name: "Diamond Grinding Wheel" },
              { id: 3, name: "Diamond Drilling Tools" },
              { id: 4, name: "Diamond Cutter" },
              { id: 5, name: "Diamond Wire Saw" },
            ],
          },
        ],
      },
      {
        id: 3,
        name: "Bags, Cases & Boxes",
        mainSubmenu: [
          {
            id: 1,
            name: "Fashion Bags",
            link: [
              { id: 1, name: "Handbags" },
              { id: 2, name: "Tote Bag" },
              { id: 3, name: "Non-woven Shopping Bag" },
              { id: 4, name: "Wallet & Purses" },
              { id: 5, name: "Bucket Bag" },
            ],
          },
          {
            id: 2,
            name: "Sports & Casual Bags",
            link: [
              { id: 1, name: "Backpack" },
              { id: 2, name: "Non Woven Bag" },
              { id: 3, name: "Waist Bag" },
              { id: 4, name: "Travel Bag" },
              { id: 5, name: "Leisure Bag" },
            ],
          },
          {
            id: 3,
            name: "Specialized Bags & Cases",
            link: [
              { id: 1, name: "Gift Box & Bag" },
              { id: 2, name: "Paper Gift Box" },
              { id: 3, name: "Mobile Phone Case" },
              { id: 4, name: "Trolley & Luggage" },
              { id: 5, name: "Cooler Bag & Box" },
              { id: 6, name: "Cosmetic Bag & Case" },
              { id: 7, name: "Laptop Bag" },
              { id: 8, name: "School Bags" },
              { id: 9, name: "Promotional Bag" },
              { id: 10, name: "Tool Bag" },
              { id: 11, name: "Garment Bag" },
              { id: 12, name: "Instrument Bag & Case" },
            ],
          },
        ],
      },
      {
        id: 4,
        name: "Furniture",
        mainSubmenu: [
          {
            id: 1,
            name: "Furniture by Use",
            link: [
              { id: 1, name: "Office Furniture" },
              { id: 2, name: "Outdoor Furniture" },
              { id: 3, name: "Living Room Furniture" },
              { id: 4, name: "Dining Room Furniture" },
              { id: 5, name: "Hospital Furniture" },
              { id: 6, name: "Bedroom Furniture" },
              { id: 7, name: "Kitchen Furniture" },
              { id: 8, name: "Store & Supermarket Furniture" },
              { id: 9, name: "Bathroom Furniture" },
              { id: 10, name: "Public Furniture" },
              { id: 11, name: "Restaurant Furniture" },
              { id: 12, name: "Salon Furniture" },
            ],
          },
          {
            id: 2,
            name: "Chairs & Tables",
            link: [
              { id: 1, name: "Dining Chairs" },
              { id: 2, name: "Office Chair" },
              { id: 3, name: "Office Desk" },
              { id: 4, name: "Dining Table" },
              { id: 5, name: "Auditorium Chairs " },
            ],
          },
          {
            id: 3,
            name: "Cabinets & Beds",
            link: [
              { id: 1, name: "Kitchen Cabinets" },
              { id: 2, name: "Hospital Bed" },
              { id: 3, name: "Bathroom Cabinets" },
              { id: 4, name: "Filing Cabinets" },
              { id: 5, name: "Bedroom Bed" },
            ],
          },
        ],
      },
      {
        id: 5,
        name: "Metallurgy, Mineral & Energy",
        mainSubmenu: [
          {
            id: 1,
            name: "Solar & Renewable Energy",
            link: [
              { id: 1, name: "Solar Panels" },
              { id: 2, name: "Solar Energy System" },
              { id: 3, name: "Solar Inverter" },
              { id: 4, name: "Solar Water Heater" },
              { id: 5, name: "Solar Collector" },
            ],
          },
          {
            id: 2,
            name: "Nonmetallic Products",
            link: [
              { id: 1, name: "Magnetic Material" },
              { id: 2, name: "Graphite & Products" },
              { id: 3, name: "Nonmetallic Minerals" },
              { id: 4, name: "Rare Earth & Products" },
              { id: 5, name: "Petroleum & Products" },
            ],
          },
          {
            id: 3,
            name: "Metal & Products",
            link: [
              { id: 1, name: "Steel & Products" },
              { id: 2, name: "Steel Pipe & Tube" },
              { id: 3, name: "Steel Coil & Strip" },
              { id: 4, name: "Steel Sheet & Plate" },
              { id: 5, name: "Stainless Steel" },
              { id: 6, name: "Aluminum" },
              { id: 7, name: "Non-ferrous Metal & Products" },
              { id: 8, name: "Copper" },
              { id: 9, name: "Alloy" },
              { id: 10, name: "Tungsten" },
              { id: 11, name: "Titanium" },
              { id: 12, name: "Black Metal & Products" },
            ],
          },
        ],
      },
      {
        id: 6,
        name: "Security & Protection",
        mainSubmenu: [
          {
            id: 1,
            name: "Surveillance & Access Control",
            link: [
              { id: 1, name: "CCTV Camera" },
              { id: 2, name: "Access Control System" },
              { id: 3, name: "Video Door Phone" },
              { id: 4, name: "DVR" },
              { id: 5, name: "Time & Attendance" },
            ],
          },
          {
            id: 2,
            name: "Roadway Safety",
            link: [
              { id: 1, name: "Traffic Barrier" },
              { id: 2, name: "Reflective Material" },
              { id: 3, name: "Probe, Sensor" },
              { id: 4, name: "Traffic Light" },
              { id: 5, name: "Road Stud" },
            ],
          },
          {
            id: 3,
            name: "Alarm & Fire Fighting",
            link: [
              { id: 1, name: "Alarm & Security Systems" },
              { id: 2, name: "Fire Hose" },
              { id: 3, name: "Fire Alarm & Smoke Detector" },
              { id: 4, name: "Alarm & Security System Accessories" },
              { id: 5, name: "Fire Sprinkler" },
            ],
          },
          {
            id: 4,
            name: "Workplace Safety Supplies",
            link: [
              { id: 1, name: "Protective Face Mask" },
              { id: 2, name: "Anti-Static" },
              { id: 3, name: "Lifesaving" },
              { id: 4, name: "EAS & Accessories" },
              { id: 5, name: "Security Guard" },
            ],
          },
        ],
      },
      {
        id: 7,
        name: "Textile",
        mainSubmenu: [
          {
            id: 1,
            name: "Fabric & Fiber",
            link: [
              { id: 1, name: "Non Woven Fabric" },
              { id: 2, name: "Industrial Textile" },
              { id: 3, name: "Synthetic Leather" },
              { id: 4, name: "Functional Textile" },
              { id: 5, name: "Knitting & Crocheting Fabric" },
              { id: 6, name: "Other Synthetic Fibers" },
              { id: 7, name: "Nylon Fabric" },
              { id: 8, name: "Silk" },
              { id: 9, name: "Traffic Light" },
              { id: 10, name: "Embroidery & Drawnwork" },
              { id: 11, name: "Linen & Flax Fabric" },
              { id: 12, name: "Polyester Fabric" },
              { id: 13, name: "Man-made Fiber" },
            ],
          },
          {
            id: 2,
            name: "Home Textile",
            link: [
              { id: 1, name: "Carpet, Rug & Mat" },
              { id: 2, name: "Towel & Handkerchief" },
              { id: 3, name: "Curtains & Drapes" },
              { id: 4, name: "Table Cloth" },
              { id: 5, name: "Decorative Cloth" },
            ],
          },
          {
            id: 3,
            name: "Textile Accessories",
            link: [
              { id: 1, name: "Yarn" },
              { id: 2, name: "Twine, Rope & Netting" },
              { id: 3, name: "Lace & Purfle" },
              { id: 4, name: "Sack & Bag for Packing" },
              { id: 5, name: "Sewing Thread" },
            ],
          },
        ],
      },
      {
        id: 8,
        name: "Instruments & Meters",
        mainSubmenu: [
          {
            id: 1,
            name: "Test & Analysis Instruments",
            link: [
              { id: 1, name: "Test Instrument" },
              { id: 2, name: "Test Machine" },
              { id: 3, name: "Analysis Instrument" },
              { id: 4, name: "Detector" },
              { id: 5, name: "Gas Analyzer" },
            ],
          },
          {
            id: 2,
            name: "Optical & Lab Instruments",
            link: [
              { id: 1, name: "Laboratory Instruments" },
              { id: 2, name: "Lab Utensil and Disposable" },
              { id: 3, name: "Optical Lens" },
              { id: 4, name: "Microscope" },
              { id: 5, name: "Telescope & Binoculars" },
            ],
          },
          {
            id: 3,
            name: "Measuring Instruments",
            link: [
              { id: 1, name: "Meter for Liquid & Gas" },
              { id: 2, name: "Weighing & Measuring Apparatus" },
              { id: 3, name: "Pressure Gauge" },
              { id: 4, name: "Meter for Electricity" },
              { id: 5, name: "Geographic Surveying Instrument" },
              { id: 6, name: "Measuring Device" },
              { id: 7, name: "Electronic Scale" },
              { id: 8, name: "Physical Measuring Meter" },
              { id: 9, name: "Water Meter" },
              { id: 10, name: "Thermometer & Hygrometer" },
              { id: 11, name: "Energy Meter & Power Meter" },
              { id: 12, name: "Multimeter" },
            ],
          },
        ],
      },
      {
        id: 9,
        name: "Office Supplies",
        mainSubmenu: [
          {
            id: 1,
            name: "Stationery",
            link: [
              { id: 1, name: "Pen, Pencil & Brush" },
              { id: 2, name: "Notebook" },
              { id: 3, name: "Drawing & Paint" },
              { id: 4, name: "File Folder" },
              { id: 5, name: "Pencil Bags & Cases" },
            ],
          },
          {
            id: 2,
            name: "Office Consumables",
            link: [
              { id: 1, name: "Drum & Toner Cartridge" },
              { id: 2, name: "Office Adhesive Tape" },
              { id: 3, name: "Office Paper" },
              { id: 4, name: "Ink Cartridge" },
              { id: 5, name: "Memo & Note Pad" },
            ],
          },
          {
            id: 3,
            name: "Office Equipments",
            link: [
              { id: 1, name: "Demonstrational & Teaching Utensil" },
              { id: 2, name: "Whiteboard" },
              { id: 3, name: "Thermal Printer" },
              { id: 4, name: "Projectors" },
              { id: 5, name: "Conferencing System" },
              { id: 6, name: "Copier & Copier Supplies" },
              { id: 7, name: "Desktop 3D Printer" },
              { id: 8, name: "Binding Machine" },
              { id: 9, name: "Projection Screen" },
              { id: 10, name: "Scanner" },
              { id: 11, name: "Calculator" },
              { id: 12, name: "Paper Shredder" },
            ],
          },
        ],
      },
      {
        id: 10,
        name: "Agriculture & Food",
        mainSubmenu: [
          {
            id: 1,
            name: "Vegetables & Fruits",
            link: [
              { id: 1, name: "Nut & Seed" },
              { id: 2, name: "Tea & Tea Leaf" },
              { id: 3, name: "Garlic" },
              { id: 4, name: "Dried Fruit" },
              { id: 5, name: "Fruit & Melon" },
              { id: 6, name: "Chilli & Pepper" },
              { id: 7, name: "Edible Fungus & Algae" },
              { id: 8, name: "Ginger" },
              { id: 9, name: "Bean & Preparation" },
              { id: 10, name: "Onion" },
              { id: 11, name: "Carrot & Radish" },
              { id: 12, name: "Potato" },
            ],
          },
          {
            id: 2,
            name: "Food & Beverage",
            link: [
              { id: 1, name: "Canned Food" },
              { id: 2, name: "Frozen Food" },
              { id: 3, name: "Beverage" },
              { id: 4, name: "Alcoholic Beverage" },
              { id: 5, name: "Sugar & Confection" },
            ],
          },
          {
            id: 3,
            name: "Additives & Extracts",
            link: [
              { id: 1, name: "Food Additive" },
              { id: 2, name: "Herbal Extract" },
              { id: 3, name: "Agriculture Manure" },
              { id: 4, name: "Feed Additives" },
              { id: 5, name: "Fruit Extract" },
            ],
          },
        ],
      },
      {
        id: 11,
        name: "Toys",
        mainSubmenu: [
          {
            id: 1,
            name: "Inflatable",
            link: [
              { id: 1, name: "Inflatable Toys" },
              { id: 2, name: "Inflatable Bouncer" },
              { id: 3, name: "Inflatable Slide" },
              { id: 4, name: "Inflatable Castle" },
              { id: 5, name: "Inflatable Cartoon" },
            ],
          },
          {
            id: 2,
            name: "Toys for Sports & Recreation",
            link: [
              { id: 1, name: "Kids Driving Toys" },
              { id: 2, name: "Vehicle Toys" },
              { id: 3, name: "Novelty Toys" },
              { id: 4, name: "Sports & Fitness" },
              { id: 5, name: "Sword & Gun Toys" },
            ],
          },
          {
            id: 3,
            name: "Toys of Material",
            link: [
              { id: 1, name: "Plush & Stuffed Toy" },
              { id: 2, name: "Plastic Toys" },
              { id: 3, name: "Remote Control Toys" },
              { id: 4, name: "Wooden Toys" },
              { id: 5, name: "Electrical Toys" },
            ],
          },
          {
            id: 4,
            name: "Toys of Special Use",
            link: [
              { id: 1, name: "Intellectual & Educational Toys" },
              { id: 2, name: "Pet Toys" },
              { id: 3, name: "Baby Toys" },
              { id: 4, name: "Model & Miniature Toys" },
              { id: 5, name: "Doll & Puppet" },
            ],
          },
        ],
      },
      {
        id: 12,
        name: "Service",
        mainSubmenu: [
          {
            id: 1,
            name: "Shipment & Storage",
            link: [
              { id: 1, name: "Shipment & Storage" },
              { id: 2, name: "Sea Freight" },
              { id: 3, name: "Freight Agents" },
              { id: 4, name: "Air Freight" },
              { id: 5, name: "Express Delivery" },
              { id: 6, name: "Railway Freight" },
              { id: 7, name: "Road Freight" },
              { id: 8, name: "Combined Transport" },
              { id: 9, name: "Warehouse Services" },
              { id: 10, name: "Customs Clearance Services" },
            ],
          },
          {
            id: 2,
            name: "Commercial Service",
            link: [
              {
                id: 1,
                name: "Certification & InspectionReal Estate & Property",
              },
              { id: 2, name: "Advertising" },
              { id: 3, name: "Consultation" },
              { id: 4, name: "Company Registration" },
            ],
          },
          {
            id: 3,
            name: "Other Services",
            link: [
              { id: 1, name: "Exhibition" },
              { id: 2, name: "Sales & Agency" },
              { id: 3, name: "Restaurant" },
              { id: 4, name: "Education & Training" },
              { id: 5, name: "Employment & Labor" },
            ],
          },
        ],
      },
    ],
  },
];
